### PR TITLE
Update librdkafka-sr.config

### PR DESCRIPTION
**Pull request by olibal**
fix for Python package confluent-kafka 1.4.2 to fix the following error messages:
- ValueError: Unrecognized properties: basic.auth.credentials.source
- ValueError: Missing required configuration property url
- ValueError: Unrecognized properties: schema.registry.basic.auth.user.info

basic.auth.credentials.source is not listed in:
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

### CODE REVIEW

**Comment by ybyzek** [comment]
@olibal IIUC the current configuration continues to work for https://github.com/confluentinc/examples/tree/5.5.0-post/clients/cloud/python with version 1.4.2.  The difference is whether client is using the new serialization API or not, and current code example uses the legacy version.  When we update https://github.com/confluentinc/examples/tree/5.5.0-post/clients/cloud/python to use the new API, we will then update this.  

(cc: @rnpridgeon to correct as needed)

**Comment by olibal** [comment]
@ybyzek thanks for clarifying. Yes, indeed, I forgot to mention in my pull request that the use case for my proposal is the new API (i.e. using confluent_kafka.SerializingProducer in conjunction with confluent_kafka.schema_registry.avro.AvroSerializer). I didn't check the legacy version.

**Comment by ybyzek** [comment]
Thanks @olibal .  Since the users will be split -- some using the new API and some not -- we should update the examples code first https://github.com/confluentinc/examples/tree/5.5.0-post/clients/cloud/python and then we'll be able to do this template here

**Comment by ybyzek** [comment]
FYI this repo is deprecated, please see https://github.com/confluentinc/configuration-templates/blob/master/README.md

So this PR will not propagate to examples.  Feel free to open a new PR for the new repo.

**Pull request closed without merging**
